apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-minio
  namespace: monitoring
spec:
  ingressClassName: traefik
  rules:
  - host: minio.node-02
    http:
      paths:
      - backend:
          service:
            name: loki-minio-console
            port:
              number: 9001
        path: /
        pathType: Prefix
