mode: daemonset

service:
  enabled: true

presets:
  logsCollection:
    enabled: false
    includeCollectorLogs: false
    storeCheckpoints: false
    maxRecombineLogSize: 102400
  hostMetrics:
    enabled: true
  kubernetesAttributes:
    enabled: true
    extractAllPodLabels: true
    extractAllPodAnnotations: true
  kubeletMetrics:
    enabled: true
  kubernetesEvents:
    enabled: true
  clusterMetrics:
    enabled: true
  annotationDiscovery:
    logs:
      enabled: false
    metrics:
      enabled: true

config:
  exporters:
    debug: {}
    otlphttp:
      compression: gzip
      encoding: proto
      metrics_endpoint: http://vmsingle-vm-single:8428/opentelemetry/v1/metrics
      logs_endpoint: http://vlsingle-vl-single:9428/insert/opentelemetry/v1/logs
      traces_endpoint: http://vtsingle-vt-single:10428/insert/opentelemetry/v1/traces
      tls:
        insecure: true
    debug/metrics:
      verbosity: detailed
    debug/traces:
      verbosity: detailed
    debug/logs:
      verbosity: detailed
    prometheus:
      endpoint: "0.0.0.0:8889"
  extensions:
    health_check:
      endpoint: ${env:MY_POD_IP}:13133
  processors:
    batch: {}
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80
      spike_limit_percentage: 25
    resourcedetection:
      detectors: [system, env] 
      system:
        hostname_sources: ["os"]
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318
          cors:
            allowed_origins:
              - "http://localhost:3000"
            allowed_headers:
              - "*"
    prometheus:
      config:
        scrape_configs:
          - job_name: 'node-exporter'
            static_configs:
            - targets: ['prometheus-prometheus-node-exporter:9100']
    journald:
      directory: /var/log/journal
  service:
    extensions:
      - health_check
    pipelines:
      logs:
        exporters:
          - otlphttp
        processors:
          - memory_limiter
          - resourcedetection
          - batch
        receivers:
          - otlp
          - journald
      metrics:
        exporters:
          - otlphttp
          - prometheus
        processors:
          - memory_limiter
          - resourcedetection
          - batch
        receivers:
          - otlp
          - prometheus
      traces:
        exporters:
          - otlphttp
        processors:
          - memory_limiter
          - resourcedetection
          - batch
        receivers:
          - otlp

image:
  #repository: "otel/opentelemetry-collector-contrib"
  repository: "otelcol"
  pullPolicy: IfNotPresent
  tag: "v1"

command:
  name: "otelcol-contrib"
  extraArgs: []

extraVolumeMounts:
  - mountPath: /var/log/journal
    name: journal
    readOnly: true

extraVolumes:
  - hostPath:
      path: /var/log/journal
      type: ""
    name: journal
