recipients:
  - id: "1000000001"
    phone_number: "010-1111-1111"
    email: "user1@example.com"
    team_name: "backend-team"
    alert_group: "dev-1"
    instance_name: "instance-1"
    alert_receive_level:
      - critical
      - warning
    notification_channels:
      - gmail
      - kakao
      - file

  - id: "1000000002"
    phone_number: "010-2222-2222"
    email: "user2@example.com"
    team_name: "backend-team"
    alert_group: "dev-1"
    instance_name: "instance-1"
    alert_receive_level:
      - warning
    notification_channels:
      - gmail
      - file  
      - kakao


  - id: "1000000003"
    phone_number: "010-3333-3333"
    email: "jaehoon.jung@kubeworks.net"
    team_name: "infra-team"
    alert_group: "infra-1"
    instance_name: "instance-2"
    alert_receive_level:
      - warning
    notification_channels:
      - gmail
      - kakao

  - id: "1000000004"
    phone_number: "010-4444-4444"
    email: "hooney.jung@gmail.com"
    team_name: "infra-team"
    alert_group: "infra-1"
    instance_name: "instance-2"
    alert_receive_level:
      - critical
      - warning
    notification_channels:
      - gmail

