---
apiVersion: v1
kind: Service
metadata:
  name: webhook
spec:
  selector:
    app: webhook
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-recipients-config
data:
  recipients.yaml: |
    recipients:
      - id: "1000000001"
        phone_number: "010-1111-1111"
        email: "user1@example.com"
        team_name: "backend-team"
        recipient_group_name: "dev-1"
        instance_name: "instance-1"
        alert_receive_level:
          - critical
          - warning
        notification_channels:
          - gmail
          - sms
          - kakao
          - file

      - id: "1000000002"
        phone_number: "010-2222-2222"
        email: "user2@example.com"
        team_name: "backend-team"
        recipient_group_name: "dev-1"
        instance_name: "instance-1"
        alert_receive_level:
          - warning
        notification_channels:
          - gmail
          - file


      - id: "1000000003"
        phone_number: "010-3333-3333"
        email: "jaehoon.jung@kubeworks.net"
        team_name: "infra-team"
        recipient_group_name: "infra-1"
        instance_name: "instance-2"
        alert_receive_level:
          - warning
        notification_channels:
          - gmail

      - id: "1000000004"
        phone_number: "010-4444-4444"
        email: "hooney.jung@gmail.com"
        team_name: "infra-team"
        recipient_group_name: "infra-1"
        instance_name: "instance-2"
        alert_receive_level:
          - critical
          - warning
        notification_channels:
          - gmail
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-app-config
data:
  LOG_LEVEL: "INFO"
  RECIPIENT_CONFIG_PATH: "/config/recipients.yaml"
  FILE_OUTPUT_PATH: "/app/logs/notification_results.log"
  UMS_API_URL: "http://ums-service.example.com:8080/api/ums"
  UMS_CHNL_SYS_CD: "AAA"
  UMS_IF_ORG_CD: "UMS"
  UMS_APPL_CD: "MUMS"
  UMS_IF_KIND_CD: "0100"
  UMS_IF_TX_CD: "10000"
  UMS_ECARE_NO: "3402"
  UMS_CHANNEL: "A"
  UMS_TMPL_TYPE: "J"
  UMS_SENDER_NAME: "Grafana"
  UMS_SENDER_PHONE: "1566-8000"
  UMS_TIMEOUT_SEC: "5"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
        - name: webhook
          image: flytux/grafana-webhook-receiver 
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: webhook-app-config
          env:
            - name: GMAIL_USER
              value: "jaehoon.jung@kubeworks.net"
            - name: GMAIL_APP_PASSWORD
              value: "owai wpqi oecn wvnm"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: recipients-config
              mountPath: /config/recipients.yaml
              subPath: recipients.yaml
              readOnly: true
      volumes:
        - name: recipients-config
          configMap:
            name: webhook-recipients-config
