---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otelcol-k8s-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otelcol-k8s-role
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - nodes/metrics
      - nodes/stats
      - services
      - endpoints
      - pods
      - namespaces
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - replicasets
    verbs: ["get", "list", "watch"]
  - nonResourceURLs:
      - /metrics
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otelcol-k8s-binding
subjects:
  - kind: ServiceAccount
    name: otelcol-k8s-sa
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: otelcol-k8s-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol-k8s-config
data:
  otelcol-k8s-config: |
    receivers:
      journald:
        directory: /var/log/journal
      filelog/otlp-json-logs:
        include:
          - /var/log/pods/*/*/*.log
        include_file_path: true
        operators:
          - id: container-parser
            type: container
      prometheus:
        config:
          scrape_configs:
          - job_name: prometheus-node-exporter
            kubernetes_sd_configs:
            - role: endpoints
            honor_labels: false
            relabel_configs:
            - action: keep
              source_labels:
              - __meta_kubernetes_service_label_app_kubernetes_io_instance
              regex: node-exporter
            - action: keep
              source_labels:
              - __meta_kubernetes_service_label_app_kubernetes_io_name
              regex: prometheus-node-exporter
            - action: keep
              source_labels:
              - __meta_kubernetes_endpoint_port_name
              regex: metrics
            - source_labels:
              - __meta_kubernetes_endpoint_address_target_kind
              - __meta_kubernetes_endpoint_address_target_name
              separator: ;
              regex: Node;(.*)
              replacement: $${1}
              target_label: node
            - source_labels:
              - __meta_kubernetes_endpoint_address_target_kind
              - __meta_kubernetes_endpoint_address_target_name
              separator: ;
              regex: Pod;(.*)
              replacement: $${1}
              target_label: pod
            - source_labels:
              - __meta_kubernetes_pod_name
              target_label: pod
            - source_labels:
              - __meta_kubernetes_pod_container_name
              target_label: container
            - source_labels:
              - __meta_kubernetes_namespace
              target_label: namespace
            - source_labels:
              - __meta_kubernetes_service_name
              target_label: service
            - source_labels:
              - __meta_kubernetes_service_name
              target_label: job
              replacement: $${1}
            - source_labels:
              - __meta_kubernetes_service_label_jobLabel
              target_label: job
              regex: (.+)
              replacement: $${1}
            - target_label: endpoint
              replacement: metrics
            metric_relabel_configs:
            - source_labels:
              - mountpoint
              regex: /var/lib/kubelet/pods.+
              action: drop
          - job_name: kube-api-server
            kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names:
                - default
            honor_labels: false
            scheme: https
            relabel_configs:
            - action: keep
              source_labels:
              - __meta_kubernetes_service_label_component
              regex: apiserver
            - action: keep
              source_labels:
              - __meta_kubernetes_service_label_provider
              regex: kubernetes
            - action: keep
              source_labels:
              - __meta_kubernetes_endpoint_port_name
              regex: https
            - source_labels:
              - __meta_kubernetes_endpoint_address_target_kind
              - __meta_kubernetes_endpoint_address_target_name
              separator: ;
              regex: Node;(.*)
              replacement: $${1}
              target_label: node
            - source_labels:
              - __meta_kubernetes_endpoint_address_target_kind
              - __meta_kubernetes_endpoint_address_target_name
              separator: ;
              regex: Pod;(.*)
              replacement: $${1}
              target_label: pod
            - source_labels:
              - __meta_kubernetes_pod_name
              target_label: pod
            - source_labels:
              - __meta_kubernetes_pod_container_name
              target_label: container
            - source_labels:
              - __meta_kubernetes_namespace
              target_label: namespace
            - source_labels:
              - __meta_kubernetes_service_name
              target_label: service
            - source_labels:
              - __meta_kubernetes_service_name
              target_label: job
              replacement: $${1}
            - source_labels:
              - __meta_kubernetes_service_label_component
              target_label: job
              regex: (.+)
              replacement: $${1}
            - target_label: endpoint
              replacement: https
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              server_name: kubernetes
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          - job_name: kube-state-metrics
            kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names:
                - monitoring
            honor_labels: true
            relabel_configs:
            - action: keep
              source_labels:
              - __meta_kubernetes_service_label_app_kubernetes_io_instance
              regex: kube-state-metrics
            - action: keep
              source_labels:
              - __meta_kubernetes_service_label_app_kubernetes_io_name
              regex: kube-state-metrics
            - action: keep
              source_labels:
              - __meta_kubernetes_endpoint_port_name
              regex: http
            - source_labels:
              - __meta_kubernetes_endpoint_address_target_kind
              - __meta_kubernetes_endpoint_address_target_name
              separator: ;
              regex: Node;(.*)
              replacement: $${1}
              target_label: node
            - source_labels:
              - __meta_kubernetes_endpoint_address_target_kind
              - __meta_kubernetes_endpoint_address_target_name
              separator: ;
              regex: Pod;(.*)
              replacement: $${1}
              target_label: pod
            - source_labels:
              - __meta_kubernetes_pod_name
              target_label: pod
            - source_labels:
              - __meta_kubernetes_pod_container_name
              target_label: container
            - source_labels:
              - __meta_kubernetes_namespace
              target_label: namespace
            - source_labels:
              - __meta_kubernetes_service_name
              target_label: service
            - source_labels:
              - __meta_kubernetes_service_name
              target_label: job
              replacement: $${1}
            - source_labels:
              - __meta_kubernetes_service_label_app_kubernetes_io_name
              target_label: job
              regex: (.+)
              replacement: $${1}
            - target_label: endpoint
              replacement: http
            metric_relabel_configs:
            - regex: (uid|container_id|image_id)
              action: labeldrop
          - job_name: cadvisor
            kubernetes_sd_configs:
            - role: node
            honor_labels: true
            honor_timestamps: false
            scrape_interval: 30s
            scrape_timeout: 5s
            metrics_path: /metrics/cadvisor
            scheme: https
            relabel_configs:
            - source_labels:
              - __meta_kubernetes_node_name
              target_label: node
            - regex: __meta_kubernetes_node_label_(.+)
              action: labelmap
            - source_labels:
              - __metrics_path__
              target_label: metrics_path
            - target_label: job
              replacement: cadvisior
            metric_relabel_configs:
            - regex: (uid)
              action: labeldrop
            - regex: (id|name)
              action: labeldrop
            - source_labels:
              - __name__
              regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
              action: drop
            tls_config:
              insecure_skip_verify: true
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          - job_name: kubelet
            kubernetes_sd_configs:
            - role: node
            honor_labels: true
            honor_timestamps: false
            scrape_interval: 30s
            scrape_timeout: 5s
            scheme: https
            relabel_configs:
            - source_labels:
              - __meta_kubernetes_node_name
              target_label: node
            - regex: __meta_kubernetes_node_label_(.+)
              action: labelmap
            - source_labels:
              - __metrics_path__
              target_label: metrics_path
            - target_label: job
              replacement: kubelet
            metric_relabel_configs:
            - regex: (uid)
              action: labeldrop
            - regex: (id|name)
              action: labeldrop
            - source_labels:
              - __name__
              regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
              action: drop
            tls_config:
              insecure_skip_verify: true
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          - job_name: k8s-probes
            kubernetes_sd_configs:
            - role: node
            honor_labels: true
            honor_timestamps: false
            scrape_interval: 30s
            scrape_timeout: 5s
            metrics_path: /metrics/probes
            scheme: https
            relabel_configs:
            - source_labels:
              - __meta_kubernetes_node_name
              target_label: node
            - regex: __meta_kubernetes_node_label_(.+)
              action: labelmap
            - source_labels:
              - __metrics_path__
              target_label: metrics_path
            - target_label: job
              replacement: kubelet
            metric_relabel_configs:
            - regex: (uid)
              action: labeldrop
            - regex: (id|name)
              action: labeldrop
            - source_labels:
              - __name__
              regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
              action: drop
            tls_config:
              insecure_skip_verify: true
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          - job_name: k8s-resources
            kubernetes_sd_configs:
            - role: node
            honor_labels: true
            honor_timestamps: false
            scrape_interval: 30s
            scrape_timeout: 5s
            metrics_path: /metrics/resource
            scheme: https
            relabel_configs:
            - source_labels:
              - __meta_kubernetes_node_name
              target_label: node
            - regex: __meta_kubernetes_node_label_(.+)
              action: labelmap
            - source_labels:
              - __metrics_path__
              target_label: metrics_path
            - target_label: job
              replacement: kubelet
            metric_relabel_configs:
            - regex: (uid)
              action: labeldrop
            - regex: (id|name)
              action: labeldrop
            - source_labels:
              - __name__
              regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
              action: drop
            tls_config:
              insecure_skip_verify: true
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    processors:
      resourcedetection:
        detectors: [ "env", "system" ]
        override: false
      attributes/add_cluster:
        actions:
          - key: cluster
            value: "node-02"
            action: insert
      k8sattributes:
    connectors:
      otlpjson:
    exporters:
      debug:
        verbosity: detailed
      otlphttp:
        endpoint: http://otelcol-gateway.monitoring:4318
        tls:
          insecure: true
    service:
      telemetry:
        logs:
          level: debug
      pipelines:
        metrics/k8s:
          receivers: [ prometheus ]
          processors: [ k8sattributes, resourcedetection, attributes/add_cluster ]
          exporters: [ otlphttp ]
        logs/jouarnald:
          receivers: [ journald ]
          processors: [ k8sattributes, resourcedetection ]
          exporters: [ otlphttp ]
        logs/raw_otlpjson:
          receivers: [ filelog/otlp-json-logs ]
          processors: [ ]
          exporters: [ otlpjson ]
        logs/otlp:
          receivers: [ otlpjson ]
          processors: [ k8sattributes, resourcedetection, attributes/add_cluster ]
          exporters: [ otlphttp ]
        logs/node:
          receivers: [ filelog/otlp-json-logs ]
          processors: [ k8sattributes, resourcedetection, attributes/add_cluster ]
          exporters: [ otlphttp ]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otelcol-k8s
spec:
  selector:
    matchLabels:
      app: otelcol-k8s
  template:
    metadata:
      labels:
        app: otelcol-k8s
    spec:
      serviceAccountName: otelcol-k8s-sa
      containers:
      - name: otelcol-k8s
        image: otelcol:v1
        command:
        - "/otelcol-contrib"
        - "--config=/conf/otelcol-k8s-config"
        ports:
        - containerPort: 4317 # OTLP gRPC
        - containerPort: 4318 # OTLP HTTP
        volumeMounts:
        - name: otelcol-k8s-config
          mountPath: /conf
        - name: journal
          mountPath: /var/log/journal
          readOnly: true
        - name: varlogpods
          mountPath: /var/log/pods
          readOnly: true
      volumes:
        - name: otelcol-k8s-config
          configMap:
            name: otelcol-k8s-config
            items:
              - key: otelcol-k8s-config
                path: otelcol-k8s-config
        - name: journal
          hostPath:
            path: /var/log/journal/
            type: Directory
        - name: varlogpods
          hostPath:
            path: /var/log/pods
