---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otelcol-gateway-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcol-gateway
spec:
  selector:
    matchLabels:
      app: otelcol-gateway
  template:
    metadata:
      labels:
        app: otelcol-gateway
    spec:
      serviceAccountName: otelcol-gateway-sa
      containers:
      - name: otelcol-gateway
        image: otelcol:v1
        command:
        - "/otelcol-contrib"
        - "--config=/conf/otelcol-gateway-config"
        ports:
        - containerPort: 4317 # OTLP gRPC
        - containerPort: 4318 # OTLP HTTP
        volumeMounts:
        - name: otelcol-gateway-config
          mountPath: /conf
      volumes:
        - name: otelcol-gateway-config
          configMap:
            name: otelcol-gateway-config
            items:
              - key: otelcol-gateway-config
                path: otelcol-gateway-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol-gateway-config
data:
  otelcol-gateway-config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch: {}
    exporters:
      debug:
        verbosity: detailed
      prometheusremotewrite:
        endpoint: http://vmsingle-vm-single:8428/api/v1/push
      otlphttp/logs:
        endpoint: http://loki-gateway.monitoring.svc.cluster.local/otlp
        tls:
          insecure: true
      otlphttp/traces:
        endpoint: http://tempo.monitoring.svc.cluster.local:4318
        tls:
          insecure: true
    service:
      telemetry:
        logs:
          level: debug
      pipelines:
        logs/otlp:
          receivers: [ otlp ]
          processors: [  ]
          exporters: [ otlphttp/logs ]
        traces/otlp:
          receivers: [ otlp ]
          processors: [  ]
          exporters: [ otlphttp/traces ]
        metrics/otlp:
          receivers: [ otlp ]
          processors: [  ]
          exporters: [ prometheusremotewrite ]
---
apiVersion: v1
kind: Service
metadata:
  name: otelcol-gateway
spec:
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  - name: otlp-http
    port: 4318
    targetPort: 4318
  selector:
    app: otelcol-gateway
