victoria-metrics-operator:
  enabled: false

defaultRules:
  create: false

vmsingle:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts: 
      - vmsingle.kw-home

alertmanager:
  enabled: false

vmalert:
  enabled: false

vmagent:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - vmagent.kw-home

grafana:
  enabled: false

prometheus-node-exporter:
  enabled: true

kube-state-metrics:
  enabled: true

kubelet:
  enabled: true

kubeApiServer:
  enabled: true

kubeControllerManager:
  enabled: true

coreDns:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false
